### ISSUE TITLE
Ilastik Launch Error

### ISSUE THREAD

**Issue by sahilm89** [ilastik/ilastik4ij#123]
Hi, 

I'm trying to run "pixel classification" from the Ilastik plugins after importing an H5 file containing the image set #0 (first time frame) of a set of 2 channel 512x512 time series images. But I get a launch error (below). I have set my application executable path to /Applications/ilastik-1.4.0-OSX.app/Contents/MacOS/ilastik. I am on Apple Mac M1. 

`[INFO] Reading available sites from https://imagej.net/
[INFO] Import dataset data starting
[INFO] Import dataset finished in 0.204 seconds
[INFO] Import dataset data starting
[INFO] Import dataset finished in 0.184 seconds
[INFO] Write input '/var/folders/j8/lrv376sd73l_40xn8sj9cwbh0000gn/T/ilastik4ij_1333942364296208606/inputs/raw_data.h5' starting
[INFO] Write input '/var/folders/j8/lrv376sd73l_40xn8sj9cwbh0000gn/T/ilastik4ij_1333942364296208606/inputs/raw_data.h5' finished
[INFO] Write inputs finished in 0.348 seconds
[INFO] Subprocess starting with arguments [/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/MacOS/ilastik, --headless, --project=pro.ilp, --output_format=hdf5, --output_axis_order=tzcyx, --input_axes=tzcyx, --readonly=1, --output_internal_path=exported_data, --export_source=Simple Segmentation, --raw_data=/var/folders/j8/lrv376sd73l_40xn8sj9cwbh0000gn/T/ilastik4ij_1333942364296208606/inputs/raw_data.h5, --output_filename_format=/var/folders/j8/lrv376sd73l_40xn8sj9cwbh0000gn/T/ilastik4ij_1333942364296208606/outputs/predictions.h5] and environment {LC_ALL=en_US.UTF-8, LAZYFLOW_TOTAL_RAM_MB=4096, LC_CTYPE=en_US.UTF-8, LANG=en_US.UTF-8}
[INFO] INFO ilastik.app: Using tiktorch executable: ['/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/MacOS/python', '-m', 'tiktorch.server']
[INFO] INFO ilastik.app: config file location: <none>
[INFO] INFO ilastik.app: Starting ilastik from "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9".
[INFO] Starting ilastik from "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9".
[INFO] INFO ilastik.app: Configuring lazyflow RAM limit to 4.0GiB
[INFO] INFO lazyflow.utility.memory: Available memory set to 4.0GiB
[INFO] WARNING backends.py:(135): RuntimeWarning: RuntimeWarning('networkx backend defined more than once: nx-loopback')
[INFO] WARNING 2023-12-29 23:38:11,101 opConservationTracking 1615 8098206464 Could not find any ILP solver
[INFO] WARNING 2023-12-29 23:38:11,108 opStructuredTracking 1615 8098206464 Could not find any ILP solver
[INFO] WARNING 2023-12-29 23:38:11,110 structuredTrackingWorkflow 1615 8098206464 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will be disabled!
[INFO] INFO ilastik.shell.projectManager: Opening Project: pro.ilp
[INFO] ERROR 2023-12-29 23:38:12,389 excepthooks 1615 8098206464 Unhandled exception in thread: 'MainThread'
[INFO] ERROR 2023-12-29 23:38:12,391 excepthooks 1615 8098206464 Traceback (most recent call last):
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/shell/projectManager.py", line 150, in openProjectFile
[INFO]     hdf5File = h5py.File(projectFilePath, mode)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/h5py/_hl/files.py", line 567, in __init__
[INFO]     fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/h5py/_hl/files.py", line 231, in make_fid
[INFO]     fid = h5f.open(name, flags, fapl=fapl)
[INFO]   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
[INFO]   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
[INFO]   File "h5py/h5f.pyx", line 106, in h5py.h5f.open
[INFO] BlockingIOError: [Errno 35] Unable to open file (unable to lock file, errno = 35, error message = 'Resource temporarily unavailable')
[INFO] 
[INFO] During handling of the above exception, another exception occurred:
[INFO] 
[INFO] Traceback (most recent call last):
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/__boot__.py", line 153, in <module>
[INFO]     _run()
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/__boot__.py", line 147, in _run
[INFO]     exec(compile(source, script, "exec"), globals(), globals())
[INFO]   File "ilastik", line 10, in <module>
[INFO]     sys.exit(main())
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik_scripts/ilastik_startup.py", line 147, in main
[INFO]     main()
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/__main__.py", line 30, in main
[INFO]     hShell = app.main(parsed_args, workflow_cmdline_args)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/app.py", line 204, in main
[INFO]     f(shell)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/app.py", line 399, in loadProject
[INFO]     shell.openProjectFile(path, parsed_args.readonly)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/shell/headless/headlessShell.py", line 94, in openProjectFile
[INFO]     hdf5File, workflow_class, readOnly = ProjectManager.openProjectFile(projectFilePath, force_readonly)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/shell/projectManager.py", line 153, in openProjectFile
[INFO]     hdf5File = h5py.File(projectFilePath, "r")
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/h5py/_hl/files.py", line 567, in __init__
[INFO]     fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/h5py/_hl/files.py", line 231, in make_fid
[INFO]     fid = h5f.open(name, flags, fapl=fapl)
[INFO]   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
[INFO]   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
[INFO]   File "h5py/h5f.pyx", line 106, in h5py.h5f.open
[INFO] BlockingIOError: [Errno 35] Unable to open file (unable to lock file, errno = 35, error message = 'Resource temporarily unavailable')
[INFO] 
[INFO] 2023-12-29 23:38:12.461 ilastik[1615:7451276] Launch error
[INFO] 2023-12-29 23:38:12.461 ilastik[1615:7451276] Launch error
[INFO] Please get in touch with the ilastik team
[ERROR] Command errored: Run Pixel Classification Prediction
java.lang.RuntimeException: Subprocess failed with exit code 255
	at org.ilastik.ilastik4ij.workflow.WorkflowCommand.lambda$runImpl$1(WorkflowCommand.java:173)
	at org.ilastik.ilastik4ij.util.StatusBar.withSpinner(StatusBar.java:76)
	at org.ilastik.ilastik4ij.workflow.WorkflowCommand.runImpl(WorkflowCommand.java:167)
	at org.ilastik.ilastik4ij.workflow.WorkflowCommand.run(WorkflowCommand.java:103)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
[INFO] Write input '/var/folders/j8/lrv376sd73l_40xn8sj9cwbh0000gn/T/ilastik4ij_8577537127023090113/inputs/raw_data.h5' starting
[INFO] Write input '/var/folders/j8/lrv376sd73l_40xn8sj9cwbh0000gn/T/ilastik4ij_8577537127023090113/inputs/raw_data.h5' finished
[INFO] Write inputs finished in 0.306 seconds
[INFO] Subprocess starting with arguments [/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/MacOS/ilastik, --headless, --project=pro.ilp, --output_format=hdf5, --output_axis_order=tzcyx, --input_axes=tzcyx, --readonly=1, --output_internal_path=exported_data, --export_source=Simple Segmentation Stage 2, --raw_data=/var/folders/j8/lrv376sd73l_40xn8sj9cwbh0000gn/T/ilastik4ij_8577537127023090113/inputs/raw_data.h5, --output_filename_format=/var/folders/j8/lrv376sd73l_40xn8sj9cwbh0000gn/T/ilastik4ij_8577537127023090113/outputs/predictions.h5] and environment {LC_ALL=en_US.UTF-8, LAZYFLOW_TOTAL_RAM_MB=4096, LC_CTYPE=en_US.UTF-8, LANG=en_US.UTF-8}
[INFO] INFO ilastik.app: Using tiktorch executable: ['/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/MacOS/python', '-m', 'tiktorch.server']
[INFO] INFO ilastik.app: config file location: <none>
[INFO] INFO ilastik.app: Starting ilastik from "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9".
[INFO] Starting ilastik from "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9".
[INFO] INFO ilastik.app: Configuring lazyflow RAM limit to 4.0GiB
[INFO] INFO lazyflow.utility.memory: Available memory set to 4.0GiB
[INFO] WARNING backends.py:(135): RuntimeWarning: RuntimeWarning('networkx backend defined more than once: nx-loopback')
[INFO] WARNING 2023-12-29 23:39:52,829 opConservationTracking 1654 8098206464 Could not find any ILP solver
[INFO] WARNING 2023-12-29 23:39:52,836 opStructuredTracking 1654 8098206464 Could not find any ILP solver
[INFO] WARNING 2023-12-29 23:39:52,838 structuredTrackingWorkflow 1654 8098206464 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will be disabled!
[INFO] INFO ilastik.shell.projectManager: Opening Project: pro.ilp
[INFO] ERROR 2023-12-29 23:39:53,919 log_exception 1654 8098206464 Traceback (most recent call last):
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/dataExport/dataExportApplet.py", line 282, in _configure_operator_with_parsed_args
[INFO]     source_index = source_choices.index(export_source)
[INFO] ValueError: 'simple segmentation stage 2' is not in list
[INFO] 
[INFO] During handling of the above exception, another exception occurred:
[INFO] 
[INFO] Traceback (most recent call last):
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/shell/projectManager.py", line 472, in _loadProject
[INFO]     self.workflow.onProjectLoaded(self)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/workflows/edgeTrainingWithMulticut/edgeTrainingWithMulticutWorkflow.py", line 289, in onProjectLoaded
[INFO]     self.dataExportApplet.configure_operator_with_parsed_args(self._data_export_args)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/dataExport/dataExportApplet.py", line 259, in configure_operator_with_parsed_args
[INFO]     self._configure_operator_with_parsed_args(parsed_args, opDataExport)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/dataExport/dataExportApplet.py", line 284, in _configure_operator_with_parsed_args
[INFO]     raise Exception(
[INFO] Exception: Invalid option for --export_source: 'Simple Segmentation Stage 2'
[INFO] Valid options are: ['multicut segmentation']
[INFO] 
[INFO] ERROR 2023-12-29 23:39:53,919 log_exception 1654 8098206464 Project could not be loaded due to the exception shown above.
[INFO] Aborting Project Open Action
[INFO] ERROR 2023-12-29 23:39:53,922 excepthooks 1654 8098206464 Unhandled exception in thread: 'MainThread'
[INFO] ERROR 2023-12-29 23:39:53,923 excepthooks 1654 8098206464 Traceback (most recent call last):
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/dataExport/dataExportApplet.py", line 282, in _configure_operator_with_parsed_args
[INFO]     source_index = source_choices.index(export_source)
[INFO] ValueError: 'simple segmentation stage 2' is not in list
[INFO] 
[INFO] During handling of the above exception, another exception occurred:
[INFO] 
[INFO] Traceback (most recent call last):
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/__boot__.py", line 153, in <module>
[INFO]     _run()
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/__boot__.py", line 147, in _run
[INFO]     exec(compile(source, script, "exec"), globals(), globals())
[INFO]   File "ilastik", line 10, in <module>
[INFO]     sys.exit(main())
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik_scripts/ilastik_startup.py", line 147, in main
[INFO]     main()
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/__main__.py", line 30, in main
[INFO]     hShell = app.main(parsed_args, workflow_cmdline_args)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/app.py", line 204, in main
[INFO]     f(shell)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/app.py", line 399, in loadProject
[INFO]     shell.openProjectFile(path, parsed_args.readonly)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/shell/headless/headlessShell.py", line 125, in openProjectFile
[INFO]     self.projectManager._loadProject(hdf5File, projectFilePath, readOnly)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/lazyflow/utility/timer.py", line 153, in wrapper
[INFO]     return func(*args, **kwargs)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/shell/projectManager.py", line 472, in _loadProject
[INFO]     self.workflow.onProjectLoaded(self)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/workflows/edgeTrainingWithMulticut/edgeTrainingWithMulticutWorkflow.py", line 289, in onProjectLoaded
[INFO]     self.dataExportApplet.configure_operator_with_parsed_args(self._data_export_args)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/dataExport/dataExportApplet.py", line 259, in configure_operator_with_parsed_args
[INFO]     self._configure_operator_with_parsed_args(parsed_args, opDataExport)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/applets/dataExport/dataExportApplet.py", line 284, in _configure_operator_with_parsed_args
[INFO]     raise Exception(
[INFO] Exception: Invalid option for --export_source: 'Simple Segmentation Stage 2'
[INFO] Valid options are: ['multicut segmentation']
[INFO] 
[INFO] 2023-12-29 23:39:53.991 ilastik[1654:7452424] Launch error
[INFO] 2023-12-29 23:39:53.991 ilastik[1654:7452424] Launch error
[INFO] Please get in touch with the ilastik team
[ERROR] Command errored: Run Autocontext Prediction
java.lang.RuntimeException: Subprocess failed with exit code 255
	at org.ilastik.ilastik4ij.workflow.WorkflowCommand.lambda$runImpl$1(WorkflowCommand.java:173)
	at org.ilastik.ilastik4ij.util.StatusBar.withSpinner(StatusBar.java:76)
	at org.ilastik.ilastik4ij.workflow.WorkflowCommand.runImpl(WorkflowCommand.java:167)
	at org.ilastik.ilastik4ij.workflow.WorkflowCommand.run(WorkflowCommand.java:103)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
[INFO] Write input '/var/folders/j8/lrv376sd73l_40xn8sj9cwbh0000gn/T/ilastik4ij_4299386264872466441/inputs/raw_data.h5' starting
[INFO] Write input '/var/folders/j8/lrv376sd73l_40xn8sj9cwbh0000gn/T/ilastik4ij_4299386264872466441/inputs/raw_data.h5' finished
[INFO] Write inputs finished in 0.396 seconds
[INFO] Subprocess starting with arguments [/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/MacOS/ilastik, --headless, --project=pro.ilp, --output_format=hdf5, --output_axis_order=tzcyx, --input_axes=tzcyx, --readonly=1, --output_internal_path=exported_data, --export_source=Simple Segmentation, --raw_data=/var/folders/j8/lrv376sd73l_40xn8sj9cwbh0000gn/T/ilastik4ij_4299386264872466441/inputs/raw_data.h5, --output_filename_format=/var/folders/j8/lrv376sd73l_40xn8sj9cwbh0000gn/T/ilastik4ij_4299386264872466441/outputs/predictions.h5] and environment {LC_ALL=en_US.UTF-8, LAZYFLOW_TOTAL_RAM_MB=4096, LC_CTYPE=en_US.UTF-8, LANG=en_US.UTF-8}
[INFO] INFO ilastik.app: Using tiktorch executable: ['/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/MacOS/python', '-m', 'tiktorch.server']
[INFO] INFO ilastik.app: config file location: <none>
[INFO] INFO ilastik.app: Starting ilastik from "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9".
[INFO] Starting ilastik from "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9".
[INFO] INFO ilastik.app: Configuring lazyflow RAM limit to 4.0GiB
[INFO] INFO lazyflow.utility.memory: Available memory set to 4.0GiB
[INFO] WARNING backends.py:(135): RuntimeWarning: RuntimeWarning('networkx backend defined more than once: nx-loopback')
[INFO] WARNING 2023-12-29 23:53:34,729 opConservationTracking 1775 8098206464 Could not find any ILP solver
[INFO] WARNING 2023-12-29 23:53:34,738 opStructuredTracking 1775 8098206464 Could not find any ILP solver
[INFO] WARNING 2023-12-29 23:53:34,740 structuredTrackingWorkflow 1775 8098206464 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will be disabled!
[INFO] ERROR 2023-12-29 23:53:35,792 excepthooks 1775 8098206464 Unhandled exception in thread: 'MainThread'
[INFO] INFO ilastik.shell.projectManager: Opening Project: pro.ilp
[INFO] ERROR 2023-12-29 23:53:35,794 excepthooks 1775 8098206464 Traceback (most recent call last):
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/shell/projectManager.py", line 150, in openProjectFile
[INFO]     hdf5File = h5py.File(projectFilePath, mode)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/h5py/_hl/files.py", line 567, in __init__
[INFO]     fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/h5py/_hl/files.py", line 231, in make_fid
[INFO]     fid = h5f.open(name, flags, fapl=fapl)
[INFO]   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
[INFO]   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
[INFO]   File "h5py/h5f.pyx", line 106, in h5py.h5f.open
[INFO] BlockingIOError: [Errno 35] Unable to open file (unable to lock file, errno = 35, error message = 'Resource temporarily unavailable')
[INFO] 
[INFO] During handling of the above exception, another exception occurred:
[INFO] 
[INFO] Traceback (most recent call last):
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/__boot__.py", line 153, in <module>
[INFO]     _run()
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/__boot__.py", line 147, in _run
[INFO]     exec(compile(source, script, "exec"), globals(), globals())
[INFO]   File "ilastik", line 10, in <module>
[INFO]     sys.exit(main())
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik_scripts/ilastik_startup.py", line 147, in main
[INFO]     main()
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/__main__.py", line 30, in main
[INFO]     hShell = app.main(parsed_args, workflow_cmdline_args)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/app.py", line 204, in main
[INFO]     f(shell)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/app.py", line 399, in loadProject
[INFO]     shell.openProjectFile(path, parsed_args.readonly)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/shell/headless/headlessShell.py", line 94, in openProjectFile
[INFO]     hdf5File, workflow_class, readOnly = ProjectManager.openProjectFile(projectFilePath, force_readonly)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/ilastik/shell/projectManager.py", line 153, in openProjectFile
[INFO]     hdf5File = h5py.File(projectFilePath, "r")
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/h5py/_hl/files.py", line 567, in __init__
[INFO]     fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
[INFO]   File "/Applications/ilastik-1.4.1b13-arm64-OSX.app/Contents/Resources/lib/python3.9/site-packages/h5py/_hl/files.py", line 231, in make_fid
[INFO]     fid = h5f.open(name, flags, fapl=fapl)
[INFO]   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
[INFO]   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
[INFO]   File "h5py/h5f.pyx", line 106, in h5py.h5f.open
[INFO] BlockingIOError: [Errno 35] Unable to open file (unable to lock file, errno = 35, error message = 'Resource temporarily unavailable')
[INFO] 
[INFO] 2023-12-29 23:53:35.862 ilastik[1775:7463072] Launch error
[INFO] 2023-12-29 23:53:35.862 ilastik[1775:7463072] Launch error
[INFO] Please get in touch with the ilastik team
[ERROR] Command errored: Run Pixel Classification Prediction
java.lang.RuntimeException: Subprocess failed with exit code 255
	at org.ilastik.ilastik4ij.workflow.WorkflowCommand.lambda$runImpl$1(WorkflowCommand.java:173)
	at org.ilastik.ilastik4ij.util.StatusBar.withSpinner(StatusBar.java:76)
	at org.ilastik.ilastik4ij.workflow.WorkflowCommand.runImpl(WorkflowCommand.java:167)
	at org.ilastik.ilastik4ij.workflow.WorkflowCommand.run(WorkflowCommand.java:103)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)`

**Comment by k-dominik** [comment]
Hi @sahilm89,

sorry you ran into problems with the plugin for ilastik. Note, I edited your post a bit to separate different plugin runs.

For Runs 1 and 3 I suspect that the file `pro.ilp` (the project file you want to run) might still be open in ilastik - this is not supported, I will amend the docs later to reflect this.

For Run 2 it seems that ilastik was closed when running the project, so opening it was successful. However, it seems that the plugin was started with the intention to run an Autocontext project, but the project at hand is a Multicut project. What kind of project should `pro.ilp` be?

Hope we can resolve this quickly.

Cheers
Dominik
