### ISSUE TITLE
Error running Ilastik

### ISSUE THREAD

**Issue by tischi** [ilastik/ilastik4ij#42]
@wolny @k-dominik 

Do you know what below error could be due to?

```
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/featureSelection/opFeatureSelection.py", line 178, in setupOutputs
[ERROR]     if self.parent.parent.featureSelectionApplet._gui is None:
[ERROR] AttributeError: 'AutocontextTwoStage' object has no attribute 'featureSelectionApplet'
[ERROR] 
[ERROR] ERROR 2020-02-20 15:41:29,034 log_exception 5027 4445873600 Project could not be loaded due to the exception shown above.
[ERROR] Aborting Project Open Action
```

**Comment by tischi** [comment]
Running it from Fiji works:

```
3D [dev] 1.6.0-scijava-3-SNAPSHOT-pre11-daily-experimental daily

nFrames = 1
[INFO] Reading available sites from https://imagej.net/
[INFO] Temporary files: {tempFileRawInput=/var/folders/91/6n93mtg108g6161n3sx_x33m0000gn/T/ilastik4j3822045189852078670_in_raw.h5, tempFileOutput=/var/folders/91/6n93mtg108g6161n3sx_x33m0000gn/T/ilastik4j2977468536716688839_out.h5}
[INFO] Exporting image of shape (1, 96, 106, 106, 2). Axis order: 'TZYXC'
[INFO] Saving as 'uint8'. Compression level: 1
[INFO] Running ilastik headless command:
[INFO] [/Applications/ilastik-1.3.3-OSX.app/Contents/MacOS/ilastik, --headless, --project=/Users/tischer/Documents/tobias-kletter/2020-02-ilastik-test/20191206_DNA_Segmentation_2Ch.ilp, --output_filename_format=/var/folders/91/6n93mtg108g6161n3sx_x33m0000gn/T/ilastik4j2977468536716688839_out.h5, --output_format=hdf5, --output_axis_order=tzyxc, --input_axes=tzyxc, /var/folders/91/6n93mtg108g6161n3sx_x33m0000gn/T/ilastik4j3822045189852078670_in_raw.h5]
[INFO] INFO lazyflow.operators.filterOperators: Using fast filters.
[ERROR] WARNING __init__.py(20): UserWarning: init: Could not import tiktorch classifier
[INFO] INFO ilastik_main: Starting ilastik from "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release".
[INFO] Starting ilastik from "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release".
[INFO] INFO ilastik_main: Configuring lazyflow RAM limit to 4.0GiB
[INFO] INFO lazyflow.utility.memory: Available memory set to 4.0GiB
[ERROR] WARNING 2020-02-20 17:34:00,384 opConservationTracking 6152 4444571072 Could not find any ILP solver
[ERROR] WARNING 2020-02-20 17:34:00,419 opStructuredTracking 6152 4444571072 Could not find any ILP solver
[ERROR] WARNING 2020-02-20 17:34:00,425 structuredTrackingWorkflow 6152 4444571072 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will be disabled!
[INFO] INFO ilastik.shell.projectManager: Opening Project: /Users/tischer/Documents/tobias-kletter/2020-02-ilastik-test/20191206_DNA_Segmentation_2Ch.ilp
[ERROR] WARNING dataset.py(313): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
[ERROR] WARNING opSimpleBlockedArrayCache.py(43): FutureWarning: Conversion of the second argument of issubdtype from `dtype` to `np.generic` is deprecated. In future, it will be treated as `np.object_ == np.dtype(dtype).type`.
[ERROR] WARNING opSlicedBlockedArrayCache.py(141): FutureWarning: Conversion of the second argument of issubdtype from `dtype` to `np.generic` is deprecated. In future, it will be treated as `np.object_ == np.dtype(dtype).type`.
[INFO] INFO ilastik.workflows.newAutocontext.newAutocontextWorkflow: Beginning Batch Processing
[INFO] INFO ilastik.applets.batchProcessing.batchProcessingApplet: Exporting to /var/folders/91/6n93mtg108g6161n3sx_x33m0000gn/T/ilastik4j2977468536716688839_out.h5/exported_data
[INFO] INFO lazyflow.operators.ioOperators.ioOperators.OpH5N5WriterBigDataset: Data shape: (1, 96, 106, 106, 2)
[INFO] INFO lazyflow.utility.bigRequestStreamer: Estimated RAM usage per pixel is 1.5KiB * safety factor (2.0)
[INFO] INFO lazyflow.utility.bigRequestStreamer: determining blockshape assuming available_ram is 3.0GiB, split between 4 threads
[INFO] INFO lazyflow.utility.bigRequestStreamer: Chose blockshape: (1, 64, 64, 63, 2)
[INFO] INFO lazyflow.utility.bigRequestStreamer: Estimated RAM usage per block is 759.9MiB
```

But running it from Java gives this error. I do not find the difference...

```
[INFO] Temporary files: {tempFileRawInput=/var/folders/91/6n93mtg108g6161n3sx_x33m0000gn/T/ilastik4j7085012432581608278_in_raw.h5, tempFileOutput=/var/folders/91/6n93mtg108g6161n3sx_x33m0000gn/T/ilastik4j2603157292498255373_out.h5}
[INFO] Exporting image of shape (1, 96, 106, 106, 2). Axis order: 'TZYXC'
[INFO] Saving as 'uint8'. Compression level: 1
[INFO] Running ilastik headless command:
[INFO] [/Applications/ilastik-1.3.3-OSX.app/Contents/MacOS/ilastik, --headless, --project=/Users/tischer/Documents/tobias-kletter/2020-02-ilastik-test/20191206_DNA_Segmentation_2Ch.ilp, --output_filename_format=/var/folders/91/6n93mtg108g6161n3sx_x33m0000gn/T/ilastik4j2603157292498255373_out.h5, --output_format=hdf5, --output_axis_order=tzyxc, /var/folders/91/6n93mtg108g6161n3sx_x33m0000gn/T/ilastik4j7085012432581608278_in_raw.h5]
[INFO] INFO lazyflow.operators.filterOperators: Using fast filters.
[ERROR] WARNING __init__.py(20): UserWarning: init: Could not import tiktorch classifier
[INFO] INFO ilastik_main: Starting ilastik from "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release".
[INFO] Starting ilastik from "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release".
[INFO] INFO ilastik_main: Configuring lazyflow RAM limit to 4.0GiB
[INFO] INFO lazyflow.utility.memory: Available memory set to 4.0GiB
[ERROR] WARNING 2020-02-20 17:43:09,975 opConservationTracking 6247 4533253568 Could not find any ILP solver
[ERROR] WARNING 2020-02-20 17:43:10,009 opStructuredTracking 6247 4533253568 Could not find any ILP solver
[ERROR] WARNING 2020-02-20 17:43:10,015 structuredTrackingWorkflow 6247 4533253568 Could not find any learning solver. Tracking will use flow-based solver (DPCT). Learning for tracking will be disabled!
[INFO] INFO ilastik.shell.projectManager: Opening Project: /Users/tischer/Documents/tobias-kletter/2020-02-ilastik-test/20191206_DNA_Segmentation_2Ch.ilp
[ERROR] WARNING dataset.py(313): H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
[ERROR] WARNING opSimpleBlockedArrayCache.py(43): FutureWarning: Conversion of the second argument of issubdtype from `dtype` to `np.generic` is deprecated. In future, it will be treated as `np.object_ == np.dtype(dtype).type`.
[ERROR] WARNING opSlicedBlockedArrayCache.py(141): FutureWarning: Conversion of the second argument of issubdtype from `dtype` to `np.generic` is deprecated. In future, it will be treated as `np.object_ == np.dtype(dtype).type`.
[INFO] INFO ilastik.workflows.newAutocontext.newAutocontextWorkflow: Beginning Batch Processing
[ERROR] ERROR 2020-02-20 17:43:16,571 log_exception 6247 4533253568 Traceback (most recent call last):
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/shell/projectManager.py", line 461, in _loadProject
[ERROR]     self.workflow.onProjectLoaded(self)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/workflows/newAutocontext/newAutocontextWorkflow.py", line 479, in onProjectLoaded
[ERROR]     self.batchProcessingApplet.run_export_from_parsed_args(self._batch_input_args)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 60, in run_export_from_parsed_args
[ERROR]     return self.run_export(role_path_dict, parsed_args.input_axes, sequence_axis=parsed_args.stack_along)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 114, in run_export
[ERROR]     progress_callback=partial(lerpProgressSignal, global_progress_start, global_progress_end),
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py", line 162, in export_dataset
[ERROR]     batch_lane.DatasetGroup[role_index].setValue(role_info)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 125, in call_in_setup_context
[ERROR]     return func(self, *args, **kwargs)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1192, in setValue
[ERROR]     self._changed()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1377, in _changed
[ERROR]     self.maybe_call_within_transaction(self._changed_impl)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1372, in maybe_call_within_transaction
[ERROR]     self.graph.maybe_call_within_transaction(fn)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/graph.py", line 143, in maybe_call_within_transaction
[ERROR]     fn()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1403, in _changed_impl
[ERROR]     c._changed()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1377, in _changed
[ERROR]     self.maybe_call_within_transaction(self._changed_impl)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1372, in maybe_call_within_transaction
[ERROR]     self.graph.maybe_call_within_transaction(fn)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/graph.py", line 143, in maybe_call_within_transaction
[ERROR]     fn()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1403, in _changed_impl
[ERROR]     c._changed()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1377, in _changed
[ERROR]     self.maybe_call_within_transaction(self._changed_impl)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1372, in maybe_call_within_transaction
[ERROR]     self.graph.maybe_call_within_transaction(fn)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/graph.py", line 143, in maybe_call_within_transaction
[ERROR]     fn()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1403, in _changed_impl
[ERROR]     c._changed()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1377, in _changed
[ERROR]     self.maybe_call_within_transaction(self._changed_impl)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1372, in maybe_call_within_transaction
[ERROR]     self.graph.maybe_call_within_transaction(fn)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/graph.py", line 143, in maybe_call_within_transaction
[ERROR]     fn()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1410, in _changed_impl
[ERROR]     self._configureOperator(self)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1423, in _configureOperator
[ERROR]     self.maybe_call_within_transaction(self.operator._setupOutputs)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1372, in maybe_call_within_transaction
[ERROR]     self.graph.maybe_call_within_transaction(fn)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/graph.py", line 143, in maybe_call_within_transaction
[ERROR]     fn()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operator.py", line 498, in _setupOutputs
[ERROR]     self.setupOutputs()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/dataSelection/opDataSelection.py", line 720, in setupOutputs
[ERROR]     self.Image.connect(op5.Output)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 125, in call_in_setup_context
[ERROR]     return func(self, *args, **kwargs)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 595, in connect
[ERROR]     self._changed()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1377, in _changed
[ERROR]     self.maybe_call_within_transaction(self._changed_impl)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1372, in maybe_call_within_transaction
[ERROR]     self.graph.maybe_call_within_transaction(fn)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/graph.py", line 143, in maybe_call_within_transaction
[ERROR]     fn()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1403, in _changed_impl
[ERROR]     c._changed()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1377, in _changed
[ERROR]     self.maybe_call_within_transaction(self._changed_impl)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1372, in maybe_call_within_transaction
[ERROR]     self.graph.maybe_call_within_transaction(fn)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/graph.py", line 143, in maybe_call_within_transaction
[ERROR]     fn()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1403, in _changed_impl
[ERROR]     c._changed()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1377, in _changed
[ERROR]     self.maybe_call_within_transaction(self._changed_impl)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1372, in maybe_call_within_transaction
[ERROR]     self.graph.maybe_call_within_transaction(fn)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/graph.py", line 143, in maybe_call_within_transaction
[ERROR]     fn()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1403, in _changed_impl
[ERROR]     c._changed()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1377, in _changed
[ERROR]     self.maybe_call_within_transaction(self._changed_impl)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1372, in maybe_call_within_transaction
[ERROR]     self.graph.maybe_call_within_transaction(fn)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/graph.py", line 143, in maybe_call_within_transaction
[ERROR]     fn()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1403, in _changed_impl
[ERROR]     c._changed()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1377, in _changed
[ERROR]     self.maybe_call_within_transaction(self._changed_impl)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1372, in maybe_call_within_transaction
[ERROR]     self.graph.maybe_call_within_transaction(fn)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/graph.py", line 143, in maybe_call_within_transaction
[ERROR]     fn()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1403, in _changed_impl
[ERROR]     c._changed()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1377, in _changed
[ERROR]     self.maybe_call_within_transaction(self._changed_impl)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1372, in maybe_call_within_transaction
[ERROR]     self.graph.maybe_call_within_transaction(fn)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/graph.py", line 143, in maybe_call_within_transaction
[ERROR]     fn()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1410, in _changed_impl
[ERROR]     self._configureOperator(self)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1423, in _configureOperator
[ERROR]     self.maybe_call_within_transaction(self.operator._setupOutputs)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/slot.py", line 1372, in maybe_call_within_transaction
[ERROR]     self.graph.maybe_call_within_transaction(fn)
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/graph.py", line 143, in maybe_call_within_transaction
[ERROR]     fn()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/lazyflow/lazyflow/operator.py", line 498, in _setupOutputs
[ERROR]     self.setupOutputs()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/featureSelection/opFeatureSelection.py", line 254, in setupOutputs
[ERROR]     super().setupOutputs()
[ERROR]   File "/Applications/ilastik-1.3.3-OSX.app/Contents/ilastik-release/ilastik-meta/ilastik/ilastik/applets/featureSelection/opFeatureSelection.py", line 178, in setupOutputs
[ERROR]     if self.parent.parent.featureSelectionApplet._gui is None:
[ERROR] AttributeError: 'AutocontextTwoStage' object has no attribute 'featureSelectionApplet'
[ERROR] 
[ERROR] ERROR 2020-02-20 17:43:16,572 log_exception 6247 4533253568 Project could not be loaded due to the exception shown above.
[ERROR] Aborting Project Open Action
```

**Comment by wolny** [comment]
hey @tischi,
this issue seems to be solved by @k-dominik recently, see: https://forum.image.sc/t/ilastik-pixel-classification-prediction-in-fiji/33182/11?u=wolny

**Comment by tischi** [comment]
hey @wolny,

I am using this within IntelliJ:

```
		<dependency>
			<groupId>org.ilastik</groupId>
			<artifactId>ilastik4ij</artifactId>
			<version>1.7.1-SNAPSHOT</version>
		</dependency>
```

And I compiled this after just having pulled `master`.
So it should work, no?

**Comment by tischi** [comment]
Maybe @k-dominik only fixed it locally and did not push the fix to this repo???

**Comment by tischi** [comment]
Or, maybe I have the wrong version of Ilastik? 
It only says`1.3.3`, how do I find the `post2` in the UI?

**Comment by wolny** [comment]
@tischi, it seems that the deployment to the maven repo wasn't configured correctly and that's why importing the `1.7.0` wasn't working. See: https://github.com/ilastik/ilastik4ij/pull/43.

Regarding:
```<dependency>
			<groupId>org.ilastik</groupId>
			<artifactId>ilastik4ij</artifactId>
			<version>1.7.1-SNAPSHOT</version>
		</dependency>
```
if you pull the `master`, build it with maven and deploy locally with `maven deploy` this import statement should work.

**Comment by tischi** [comment]
It does not work :-(
Any pointers? 
Do you know which lines in the ilastik4ij source code are the critical ones for the bug to disappear?

**Comment by wolny** [comment]
Are you able to import `1.7.1-SNAPSHOT` that contains @k-dominik's fix (https://forum.image.sc/t/ilastik-pixel-classification-prediction-in-fiji/33182/9?u=wolny)? Is the problem still there when using the latest jar?

**Comment by wolny** [comment]
In your logs (when running from Java) you have:
```
[INFO] Running ilastik headless command:
[INFO] [/Applications/ilastik-1.3.3-OSX.app/Contents/MacOS/ilastik, --headless, --project=/Users/tischer/Documents/tobias-kletter/2020-02-ilastik-test/20191206_DNA_Segmentation_2Ch.ilp, --output_filename_format=/var/folders/91/6n93mtg108g6161n3sx_x33m0000gn/T/ilastik4j2603157292498255373_out.h5, --output_format=hdf5, --output_axis_order=tzyxc, /var/folders/91/6n93mtg108g6161n3sx_x33m0000gn/T/ilastik4j7085012432581608278_in_raw.h5]
```
where `--input_axes=tzyxc` is missing.
This option is present when you run it with Fiji (your first log), due to @k-dominik's recent fix

**Comment by tischi** [comment]
I still think it is missing from this repo, see here:

https://github.com/ilastik/ilastik4ij/blob/cecbc6fff55195deeaf13bbaff1188958417b270/src/main/java/org/ilastik/ilastik4ij/executors/PixelClassification.java#L28

no trace of `--input_axes=tzyxc`

**Comment by tischi** [comment]
I still think it is missing from this repo, see here:

https://github.com/ilastik/ilastik4ij/blob/cecbc6fff55195deeaf13bbaff1188958417b270/src/main/java/org/ilastik/ilastik4ij/executors/PixelClassification.java#L28

no trace of `--input_axes=tzyxc`

**Comment by tischi** [comment]
I take it back:
https://github.com/ilastik/ilastik4ij/blob/cecbc6fff55195deeaf13bbaff1188958417b270/src/main/java/org/ilastik/ilastik4ij/executors/PixelClassification.java#L39

**Comment by tischi** [comment]
This is the explanation:

<img width="1529" alt="image" src="https://user-images.githubusercontent.com/2157566/75269769-b8601800-57f9-11ea-8b3a-d3cb269cda1d.png">

**Comment by wolny** [comment]
Ah so you took my fork :) is it working with the upstream then?

**Comment by tischi** [comment]
works with upstream
