### ISSUE TITLE
Error when running pixel prediction

### ISSUE THREAD

**Issue by tischi** [ilastik/ilastik4ij#79]
@k-dominik 

We were running this IJ Macro code:
```
open("/Users/tischer/Desktop/magdalena-schindler/3D_Sample.tif");
run("Split Channels");
selectWindow("C1-3D_Sample.tif");
run("Configure ilastik executable location", "executablefile=/Applications/ilastik-1.3.3post2-OSX.app/Contents/MacOS/ilastik numthreads=-1 maxrammb=4096");
```

And got below error, can you help?

```
WARNING: core mtj jar files are not available as resources to this classloader (sun.misc.Launcher$AppClassLoader@764c12b6)
[INFO] Exporting image of shape (1, 30, 530, 648, 1). Axis order: 'TZYXC'
[INFO] Saving as 'uint8'. Compression level: 2
[INFO] Exporting image to HDF5 dataset took: 5137
[INFO] Temporary files: {tempFileRawInput=/var/folders/91/6n93mtg108g6161n3sx_x33m0000gn/T/ilastik4j225243265060090024_in_raw.h5, tempFileOutput=/var/folders/91/6n93mtg108g6161n3sx_x33m0000gn/T/ilastik4j3904737484356056740_out.h5}
[INFO] Exporting image of shape (1, 30, 530, 648, 1). Axis order: 'TZYXC'
[INFO] Saving as 'uint8'. Compression level: 1
[INFO] Running ilastik headless command:
[INFO] [/Applications/ilastik-1.3.3post2-OSX.app/Contents/MacOS/ilastik, --headless, --project=/Volumes/cba/exchange/LenaSchindler/pix-class.ilp, --output_format=hdf5, --output_axis_order=tzyxc, --input_axes=tzyxc, --readonly=1, --output_internal_path=exported_data, --input_axes=tzyxc, --export_source=Simple Segmentation, --raw_data=/var/folders/91/6n93mtg108g6161n3sx_x33m0000gn/T/ilastik4j225243265060090024_in_raw.h5, --output_filename_format=/var/folders/91/6n93mtg108g6161n3sx_x33m0000gn/T/ilastik4j3904737484356056740_out.h5]
[ERROR] usage: ilastik.py [-h] [--headless] [--project PROJECT] [--readonly]
[ERROR]                   [--new_project NEW_PROJECT] [--workflow WORKFLOW]
[ERROR]                   [--clean_paths] [--redirect_output REDIRECT_OUTPUT]
[ERROR]                   [--debug] [--logfile LOGFILE] [--process_name PROCESS_NAME]
[ERROR]                   [--configfile CONFIGFILE] [--fullscreen] [--exit_on_failure]
[ERROR]                   [--hbp]
[ERROR] ilastik.py: error: argument --readonly: ignored explicit argument '1'
[ERROR] ilastik execution crashed
[INFO] Deleted tmp file: /var/folders/91/6n93mtg108g6161n3sx_x33m0000gn/T/ilastik4j225243265060090024_in_raw.h5
[ERROR] Module threw exception
java.lang.RuntimeException: Execution of ilastik was not successful.
	at org.ilastik.ilastik4ij.executors.AbstractIlastikExecutor.executeCommandLine(AbstractIlastikExecutor.java:178)
	at org.ilastik.ilastik4ij.executors.AbstractIlastikExecutor.executeIlastik(AbstractIlastikExecutor.java:105)
	at org.ilastik.ilastik4ij.executors.PixelClassification.classifyPixels(PixelClassification.java:24)
	at org.ilastik.ilastik4ij.ui.IlastikPixelClassificationCommand.runClassification(IlastikPixelClassificationCommand.java:72)
	at org.ilastik.ilastik4ij.ui.IlastikPixelClassificationCommand.run(IlastikPixelClassificationCommand.java:60)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

```
(Fiji Is Just) ImageJ 2.1.0/1.53c; Java 1.8.0_202 [64-bit]; Mac OS X 10.14.6; 2979MB of 10041MB (29%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Execution of ilastik was not successful.
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:65)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Execution of ilastik was not successful.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.RuntimeException: Execution of ilastik was not successful.
	at org.ilastik.ilastik4ij.executors.AbstractIlastikExecutor.executeCommandLine(AbstractIlastikExecutor.java:178)
	at org.ilastik.ilastik4ij.executors.AbstractIlastikExecutor.executeIlastik(AbstractIlastikExecutor.java:105)
	at org.ilastik.ilastik4ij.executors.PixelClassification.classifyPixels(PixelClassification.java:24)
	at org.ilastik.ilastik4ij.ui.IlastikPixelClassificationCommand.runClassification(IlastikPixelClassificationCommand.java:72)
	at org.ilastik.ilastik4ij.ui.IlastikPixelClassificationCommand.run(IlastikPixelClassificationCommand.java:60)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

**Comment by k-dominik** [comment]
Hi @tischi,

the plugin is unfortunately _not_ compatible with all ilastik versions (see also our [compatibility note](https://github.com/ilastik/ilastik4ij#installation). The one you are using, is unfortunately in this range of versions :/. Upgrading is the way to go.

**Comment by tischi** [comment]
Thanks!
